config/routes.rb
Rails.application.routes.draw do


  root to: 'pages#index'
  
  get 'welcome', to: 'welcome#index'
  

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :blogs do 
    member do
      get :toggle_status
    end
  end
  
  # get 'statement', to: "amol361s#index"
  
  resources :amol361s, path: 'statements' do 
		member do 
			put :hide
		end
	end

	put "unhide_all_amol361" => "amol361s#unhide_all"


	resources :amol361s do 
		collection { post :import }
	end

	get "remove_all_amol361s" => "amol361s#remove_all"
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <strong><a href="#">Office Management System</a></strong>
    by <em><a href="#">Yaseen Kola</a></em>
  </small>
</footer>

app/views/layouts/_messages.html.erb
<div style="margin-top: 23px;" >
  
<div id="fade-out-target">
    
<% flash.each do |message_type, message| %>
 <div class="alert alert-<%= flash_class_name(message_type) %> alert-dismissable">
  <span><center><%= message %></center></span>
  <!--<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>-->
 </div>
 
 </div>
 
<% end %>

</div>

<!--<div style="margin-top: 23px;" >
  
<div id="fade-out-target">
  
<% flash.each do |name, msg| %>

<div class='alert alert-<%="#{name}" %>' role="alert">

<a href="#" class="close" data-dismiss="alert">×</a>

<%= content_tag :div, msg, :id => "flash_#{name}", :class => "center flash_color" if msg.is_a?(String) %>

</div>

</div>

<% end %>

</div>-->

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">
  <b><%= link_to "FOOTLOOSE", root_path, class: "navbar-brand", id: "logo" %></b>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
   
    
  <% if user_signed_in? -%>
  
     <ul class="navbar-nav mr-auto">
       
         <li class="nav-item">
           <%= active_link_to "Statement", amol361s_path, class: "nav-link" %>
         </li>
         
        <!-- <li class="nav-item">-->
        <!--   <%= active_link_to "Ehsan", "#", class: "nav-link" %>-->
        <!-- </li>-->
         
        <!--<li class="nav-item dropdown">-->
        <!--<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
        <!--    Blogs-->
        <!--</a>-->
        <!--<div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
        <!--  <%= active_link_to "New Blog", new_blog_path, class: "dropdown-item" %>-->
        <!--  <%= active_link_to "All Blogs", blogs_path, class: "dropdown-item" %>-->
        <!--</li>-->
       
     </ul>
     
     
     <ul class="navbar-nav ml-auto">
       
          <li class="nav-item nav-link" style="color: white;font-weight: bold;">
            
             Logged in as: <span class="badge">
               
                             <%= active_link_to current_user.username, edit_user_registration_path %> 
            
                           </span>

          </li>
     
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
     </ul>
     
	<% else %>
	
		 <ul class="navbar-nav ml-auto">
         <li class="nav-item">
           <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
         </li>
         <li class="nav-item">
           <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
         </li>
     </ul>
	 
  <% end %>
		 
      
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Footloose OMS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    
    <div class="container">
      
      <%= render 'layouts/messages' %>
    
    </div>
    
    <div class="container">
      
      <%= yield %>
    
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>


<script>
$(document).ready(function() {
	$('td:contains("Not Delivered")').css('color', 'red');
	$('td:contains("DELIVERED ON")').css('color', 'green');
	$('td:contains("DELIVERED")').css('color', 'green'); 
	$('td:contains("BY HAND")').css('color', 'green'); 
	$('td:contains("VIA DUBAI")').css('color', 'green'); 
	$('td:contains("DOWNPAYMENT")').css('color', '#09c5da'); 
	$('td:contains("DIRECT")').css('color', 'green'); 
	$('td:contains("DUBAI WAREHOUSE")').css('color', '#FF0000'); 
	$('td:contains("D.N")').css('color', 'green');  
	$('td:contains("CHINA READY GOODS")').css('color', '#b98f1a'); 
	$('td:contains("CANCELLED")').css('color', 'darkred').css('font-weight','bold'); 
	$('td:contains("FOOT LOOSE")').css('color', '#3da93d').css('font-weight','bold'); 
	$('td:contains("GLOBAL FEET")').css('color', 'darkred').css('font-weight','bold'); 
	$('td:contains("NOT ASSIGNED")').css('color', '#498ca0').css('font-weight','bold'); 
	$('td:contains("DUBAI PORT")').css('color', '#f9e2d4').css('font-weight','bold'); 
	$('td:contains("5%")').css('color', '#778bd2').css('font-weight','bold'); 
	$('td:contains("PI.")').css('color', '#ea10ba').css('font-weight','bold');
});
</script>